# Generated by Django 4.2.16 on 2024-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.CharField(default='Rp5vd34d-z4', max_length=255),
        ),
    ]
